import type { Metadata } from 'next'

import './globals.css'
import Modal from '@/components/Modal'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Trello 2.0 clone',
  description: 'Generated by Rohit Renke',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-[#F5F6f8]'>{children}
      <Modal/></body>
    </html>
  )
}

